# Generated by Django 6.0.1 on 2026-01-27 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('frequency', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_at', models.DateTimeField()),
                ('was_taken', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracking.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('medication', 'Medication'), ('exercise', 'Exercise'), ('sleep', 'Sleep Log'), ('diary', 'Diary Entry'), ('general', 'General')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('time_of_day', models.TimeField()),
                ('days_of_week', models.JSONField(default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('linked_medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='tracking.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField()),
                ('label_tr', models.CharField(max_length=150)),
                ('label_en', models.CharField(max_length=150)),
                ('input_type', models.CharField(choices=[('slider', 'Slider (0-10)'), ('boolean', 'Yes/No'), ('choice', 'Multiple Choice'), ('text', 'Free Text'), ('number', 'Numeric')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('disease_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_definitions', to='patients.diseasemodule')),
            ],
            options={
                'ordering': ['disease_module', 'order'],
                'unique_together': {('disease_module', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_date', models.DateField()),
                ('value', models.JSONField()),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_entries', to=settings.AUTH_USER_MODEL)),
                ('symptom_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracking.symptomdefinition')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', '-recorded_date'], name='tracking_sy_patient_90b7c2_idx'), models.Index(fields=['symptom_definition', 'patient'], name='tracking_sy_symptom_376e7d_idx')],
                'unique_together': {('patient', 'symptom_definition', 'recorded_date')},
            },
        ),
    ]
