# Generated by Django 5.1.5 on 2026-03-15 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_tr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description_tr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sleep Category',
                'verbose_name_plural': 'Sleep Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SleepTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('content_tr', models.TextField(max_length=500)),
                ('content_en', models.TextField(max_length=500)),
                ('icon', models.CharField(blank=True, default='moon', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sleep Tip',
                'verbose_name_plural': 'Sleep Tips',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SleepFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_tr', models.CharField(max_length=300)),
                ('question_en', models.CharField(max_length=300)),
                ('answer_tr', models.TextField()),
                ('answer_en', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='sleep.sleepcategory')),
            ],
            options={
                'verbose_name': 'Sleep FAQ',
                'verbose_name_plural': 'Sleep FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SleepArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('article_type', models.CharField(choices=[('general', 'Genel Bilgi'), ('disorder', 'Uyku Bozuklugu'), ('hygiene', 'Uyku Hijyeni'), ('diagnosis', 'Tani Yontemi'), ('disease_sleep', 'Hastalikta Uyku'), ('tip', 'Pratik Oneri')], default='general', max_length=20)),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('subtitle_tr', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=300)),
                ('content_tr', models.TextField()),
                ('content_en', models.TextField()),
                ('summary_tr', models.TextField(blank=True, default='', max_length=500)),
                ('summary_en', models.TextField(blank=True, default='', max_length=500)),
                ('related_disease', models.CharField(blank=True, default='', help_text='migraine, epilepsy, alzheimer, parkinson, diabetes, adhd', max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sleep/covers/')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title_tr', models.CharField(blank=True, default='', max_length=200)),
                ('meta_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description_tr', models.TextField(blank=True, default='', max_length=300)),
                ('meta_description_en', models.TextField(blank=True, default='', max_length=300)),
                ('references', models.TextField(blank=True, default='', help_text='Kaynak ve referanslar (her satir bir referans)')),
                ('author_name', models.CharField(blank=True, default='Norosera Editoryel Ekibi', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sleep.sleepcategory')),
            ],
            options={
                'verbose_name': 'Sleep Article',
                'verbose_name_plural': 'Sleep Articles',
                'ordering': ['category__order', 'order', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='sleep_sleep_slug_1658fd_idx'), models.Index(fields=['article_type'], name='sleep_sleep_article_5414c5_idx'), models.Index(fields=['related_disease'], name='sleep_sleep_related_c6cc9f_idx'), models.Index(fields=['is_published', '-created_at'], name='sleep_sleep_is_publ_da7cb7_idx')],
            },
        ),
    ]
