# Generated by Django 5.1.5 on 2026-03-15 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepScreeningQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_tr', models.CharField(max_length=500)),
                ('question_en', models.CharField(max_length=500)),
                ('help_text_tr', models.CharField(blank=True, default='', max_length=500)),
                ('help_text_en', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Screening Question',
                'verbose_name_plural': 'Screening Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SleepScreeningTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('instructions_tr', models.TextField(blank=True, default='')),
                ('instructions_en', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='clipboard-list', max_length=50)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sleep Screening Test',
                'verbose_name_plural': 'Sleep Screening Tests',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SleepScreeningOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_tr', models.CharField(max_length=300)),
                ('text_en', models.CharField(max_length=300)),
                ('score', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sleep.sleepscreeningquestion')),
            ],
            options={
                'verbose_name': 'Screening Option',
                'verbose_name_plural': 'Screening Options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SleepScreeningResultRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('low', 'Düşük Risk'), ('moderate', 'Orta Risk'), ('high', 'Yüksek Risk'), ('severe', 'Çok Yüksek Risk')], max_length=20)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('recommendation_tr', models.TextField(blank=True, default='')),
                ('recommendation_en', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='green', help_text='Tailwind renk adı: green, yellow, orange, red', max_length=30)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_ranges', to='sleep.sleepscreeningtest')),
            ],
            options={
                'verbose_name': 'Screening Result Range',
                'verbose_name_plural': 'Screening Result Ranges',
                'ordering': ['min_score'],
            },
        ),
        migrations.AddField(
            model_name='sleepscreeningquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sleep.sleepscreeningtest'),
        ),
    ]
