# Generated by Django 5.1.5 on 2026-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_sleepscreeningquestion_sleepscreeningtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeparticle',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='Harici görsel URL (Unsplash vb.). cover_image boşsa kullanılır.', max_length=500),
        ),
    ]
