# Generated by Django 6.0.1 on 2026-01-27 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigraineTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_tr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('dietary', 'Dietary'), ('environmental', 'Environmental'), ('hormonal', 'Hormonal'), ('emotional', 'Emotional'), ('physical', 'Physical'), ('sleep', 'Sleep'), ('other', 'Other')], max_length=20)),
                ('is_predefined', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='MigraineAttack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('intensity', models.PositiveSmallIntegerField(help_text='Pain intensity 1-10')),
                ('pain_location', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('bilateral', 'Bilateral'), ('frontal', 'Frontal'), ('occipital', 'Occipital'), ('other', 'Other')], default='', max_length=20)),
                ('has_aura', models.BooleanField(default=False)),
                ('has_nausea', models.BooleanField(default=False)),
                ('has_vomiting', models.BooleanField(default=False)),
                ('has_photophobia', models.BooleanField(default=False)),
                ('has_phonophobia', models.BooleanField(default=False)),
                ('medication_taken', models.CharField(blank=True, default='', max_length=200)),
                ('medication_effective', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migraine_attacks', to=settings.AUTH_USER_MODEL)),
                ('triggers_identified', models.ManyToManyField(blank=True, related_name='attacks', to='migraine.migrainetrigger')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['patient', '-start_datetime'], name='migraine_mi_patient_0e3aef_idx')],
            },
        ),
    ]
