# Generated by Django 6.0.1 on 2026-01-28 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(help_text='Ozellik ismi', max_length=200)),
                ('is_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled_for_roles', models.JSONField(blank=True, default=list, help_text='Bos ise herkese acik. ["patient","doctor"] gibi roller belirtilebilir.')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(help_text='Admin panelinde gorunecek isim', max_length=200)),
                ('value', models.TextField(default='')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=10)),
                ('description', models.TextField(blank=True, default='', help_text='Parametre aciklamasi')),
                ('category', models.CharField(default='general', help_text='Gruplama icin kategori', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='True ise frontend API uzerinden erisilebilir')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Configs',
                'ordering': ['category', 'key'],
            },
        ),
    ]
