# Generated by Django 5.1.5 on 2026-02-13 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_featureflag_siteconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(max_length=50)),
                ('task_type', models.CharField(choices=[('generate_content', 'Icerik Uret'), ('generate_news', 'Haber Uret'), ('optimize_seo', 'SEO Optimize'), ('check_quality', 'Kalite Kontrol'), ('review_article', 'Yazi Degerlendir'), ('find_media', 'Gorsel Bul'), ('add_links', 'Link Ekle'), ('edit_content', 'Icerik Duzenle'), ('scan_trends', 'Trend Tara'), ('analyze_competitor', 'Rakip Analiz'), ('full_pipeline', 'Tam Pipeline')], max_length=30)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('running', 'Calisiyor'), ('completed', 'Tamamlandi'), ('failed', 'Basarisiz'), ('skipped', 'Atlandi'), ('cancelled', 'Iptal Edildi')], default='pending', max_length=15)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('llm_provider', models.CharField(blank=True, default='', max_length=20)),
                ('llm_model', models.CharField(blank=True, default='', max_length=50)),
                ('article_id', models.UUIDField(blank=True, null=True)),
                ('news_article_id', models.UUIDField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='common.agenttask')),
            ],
            options={
                'verbose_name': 'Ajan Gorevi',
                'verbose_name_plural': 'Ajan Gorevleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_name', 'status'], name='common_agen_agent_n_916cfb_idx'), models.Index(fields=['task_type', 'created_at'], name='common_agen_task_ty_64fb0f_idx')],
            },
        ),
    ]
