# Generated by Django 5.1.5 on 2026-02-15 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_agenttask_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('message_tr', models.TextField(max_length=500)),
                ('message_en', models.TextField(blank=True, default='', max_length=500)),
                ('link_url', models.URLField(blank=True, default='')),
                ('link_text_tr', models.CharField(blank=True, default='', max_length=50)),
                ('link_text_en', models.CharField(blank=True, default='', max_length=50)),
                ('bg_color', models.CharField(default='#1B4F72', help_text='HEX renk kodu', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('is_active', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Yuksek = once gosterilir')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageHero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle_tr', models.TextField(max_length=500)),
                ('subtitle_en', models.TextField(blank=True, default='', max_length=500)),
                ('cta_text_tr', models.CharField(default='Hemen Basla', max_length=50)),
                ('cta_text_en', models.CharField(default='Get Started', max_length=50)),
                ('cta_url', models.CharField(default='/auth/register', max_length=200)),
                ('secondary_cta_text_tr', models.CharField(blank=True, default='', max_length=50)),
                ('secondary_cta_text_en', models.CharField(blank=True, default='', max_length=50)),
                ('secondary_cta_url', models.CharField(blank=True, default='', max_length=200)),
                ('background_image', models.ImageField(blank=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Anasayfa Hero',
                'verbose_name_plural': 'Anasayfa Hero',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('github', 'GitHub')], max_length=20, unique=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sosyal Medya',
                'ordering': ['order'],
            },
        ),
    ]
