# Generated by Django 5.1.5 on 2026-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_announcement_homepagehero_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='task_type',
            field=models.CharField(choices=[('generate_content', 'Icerik Uret'), ('generate_news', 'Haber Uret'), ('optimize_seo', 'SEO Optimize'), ('check_quality', 'Kalite Kontrol'), ('review_article', 'Yazi Degerlendir'), ('find_media', 'Gorsel Bul'), ('add_links', 'Link Ekle'), ('edit_content', 'Icerik Duzenle'), ('scan_trends', 'Trend Tara'), ('analyze_competitor', 'Rakip Analiz'), ('full_pipeline', 'Tam Pipeline'), ('legal_check', 'Hukuki Kontrol'), ('translate', 'Ceviri'), ('marketing_content', 'Pazarlama Icerik'), ('visual_brief', 'Gorsel Brief'), ('schedule_plan', 'Yayin Plani')], max_length=30),
        ),
    ]
