# Generated by Django 5.1.5 on 2026-02-15 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_add_marketing_task_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Kampanya basligi', max_length=200)),
                ('theme', models.CharField(help_text='Ana tema', max_length=300)),
                ('week_start', models.DateField(help_text='Hafta baslangici')),
                ('status', models.CharField(choices=[('generating', 'Uretiyor'), ('review', 'Inceleme Bekliyor'), ('approved', 'Onaylandi'), ('scheduled', 'Planlandi'), ('published', 'Yayinlandi'), ('archived', 'Arsivlendi')], default='generating', max_length=15)),
                ('platforms', models.JSONField(default=list, help_text='["instagram", "linkedin", "twitter"]')),
                ('language', models.CharField(default='tr', max_length=5)),
                ('tone', models.CharField(default='educational', max_length=20)),
                ('target_audience', models.CharField(default='patients', max_length=20)),
                ('content_output', models.JSONField(blank=True, default=dict, help_text='Marketing Content Agent ciktisi')),
                ('visual_briefs', models.JSONField(blank=True, default=dict, help_text='Visual Brief Agent ciktisi')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='Scheduling Agent ciktisi')),
                ('edited_content', models.JSONField(blank=True, default=dict, help_text='Admin tarafindan duzenlenmis icerik')),
                ('editor_notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
                ('pipeline_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to='common.agenttask')),
            ],
            options={
                'verbose_name': 'Marketing Kampanyasi',
                'verbose_name_plural': 'Marketing Kampanyalari',
                'ordering': ['-week_start', '-created_at'],
            },
        ),
    ]
