# Generated by Django 5.1.5 on 2026-03-12 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_add_marketing_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenLinkScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Calisiyor'), ('completed', 'Tamamlandi'), ('failed', 'Basarisiz')], default='running', max_length=15)),
                ('total_links_checked', models.PositiveIntegerField(default=0)),
                ('broken_links_found', models.PositiveIntegerField(default=0)),
                ('auto_fixed_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Link Taramasi',
                'verbose_name_plural': 'Link Taramalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokenLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broken_url', models.URLField(max_length=2000)),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP yanit kodu (404, 500, vb.)', null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('link_type', models.CharField(choices=[('internal', 'Dahili'), ('external', 'Harici'), ('image', 'Gorsel'), ('video', 'Video')], default='external', max_length=10)),
                ('source_type', models.CharField(choices=[('article', 'Blog Yazisi'), ('news', 'Haber'), ('education', 'Egitim Icerigi'), ('announcement', 'Duyuru'), ('social_link', 'Sosyal Medya')], max_length=20)),
                ('source_id', models.UUIDField(help_text='Kaynak icerigin UUID si')),
                ('source_title', models.CharField(blank=True, default='', max_length=300)),
                ('source_field', models.CharField(help_text='Linkin bulundugu alan (body_tr, video_url, vb.)', max_length=50)),
                ('source_language', models.CharField(blank=True, default='', max_length=5)),
                ('status', models.CharField(choices=[('detected', 'Tespit Edildi'), ('auto_fixed', 'Otomatik Tamir'), ('ai_suggested', 'AI Onerisi Var'), ('manually_fixed', 'Manuel Tamir'), ('ignored', 'Yok Sayildi')], default='detected', max_length=15)),
                ('suggested_url', models.URLField(blank=True, default='', max_length=2000)),
                ('fix_notes', models.TextField(blank=True, default='')),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('check_count', models.PositiveIntegerField(default=1)),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirik Link',
                'verbose_name_plural': 'Kirik Linkler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='common_brok_status_c27cbe_idx'), models.Index(fields=['source_type', 'source_id'], name='common_brok_source__578edb_idx')],
                'unique_together': {('broken_url', 'source_type', 'source_id', 'source_field')},
            },
        ),
    ]
