# Generated by Django 5.1.5 on 2026-02-15 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('account_name', models.CharField(help_text='Hesap adi / sayfa adi', max_length=200)),
                ('account_id', models.CharField(help_text='Platform hesap ID', max_length=200)),
                ('access_token', models.TextField(help_text='Access token')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, default='', help_text='Facebook Page ID (Instagram icin)', max_length=200)),
                ('organization_urn', models.CharField(blank=True, default='', help_text='LinkedIn Organization URN', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Token Suresi Dolmus'), ('disconnected', 'Baglanti Kesildi'), ('pending_review', 'App Review Bekliyor')], default='active', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('total_posts_published', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sosyal Medya Hesabi',
                'verbose_name_plural': 'Sosyal Medya Hesaplari',
                'ordering': ['platform', 'account_name'],
                'unique_together': {('platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='SocialCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(help_text='Ana tema', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('platforms', models.JSONField(default=list, help_text='["instagram", "linkedin"]')),
                ('posts_per_platform', models.PositiveIntegerField(default=3)),
                ('language', models.CharField(default='tr', max_length=5)),
                ('tone', models.CharField(default='educational', max_length=20)),
                ('target_audience', models.CharField(default='patients', max_length=30)),
                ('week_start', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('generating', 'AI Uretiyor'), ('review', 'Onay Bekliyor'), ('partially_approved', 'Kismen Onayli'), ('approved', 'Tumu Onayli'), ('scheduled', 'Zamanlandi'), ('in_progress', 'Yayinlaniyor'), ('completed', 'Tamamlandi'), ('archived', 'Arsiv')], default='draft', max_length=20)),
                ('content_output', models.JSONField(blank=True, default=dict)),
                ('schedule_output', models.JSONField(blank=True, default=dict)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sosyal Medya Kampanyasi',
                'verbose_name_plural': 'Sosyal Medya Kampanyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('post_format', models.CharField(choices=[('single_image', 'Tek Gorsel'), ('carousel', 'Carousel / Galeri'), ('video', 'Video'), ('text_only', 'Sadece Metin'), ('reel', 'Reel'), ('story', 'Story')], default='single_image', max_length=20)),
                ('caption_tr', models.TextField(help_text='Turkce post metni')),
                ('caption_en', models.TextField(blank=True, default='', help_text='Ingilizce post metni')),
                ('hashtags', models.JSONField(default=list, help_text='["#norosera", "#noroloji"]')),
                ('image_urls', models.JSONField(default=list, help_text='Gorsel URL listesi')),
                ('image_prompt', models.TextField(blank=True, default='', help_text="AI gorsel uretim prompt'u")),
                ('visual_brief', models.JSONField(blank=True, default=dict, help_text='Gorsel brief detaylari')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Yayinlanma zamani', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('generating', 'AI Uretiyor'), ('review', 'Onay Bekliyor'), ('approved', 'Onaylandi'), ('scheduled', 'Zamanlandi'), ('publishing', 'Yayinlaniyor'), ('published', 'Yayinlandi'), ('failed', 'Basarisiz'), ('archived', 'Arsivlendi')], default='draft', max_length=15)),
                ('platform_post_id', models.CharField(blank=True, default='', help_text='Instagram/LinkedIn post ID', max_length=200)),
                ('platform_url', models.URLField(blank=True, default='', help_text='Yayinlanan post URL')),
                ('publish_error', models.TextField(blank=True, default='')),
                ('edited_caption', models.TextField(blank=True, default='', help_text='Admin tarafindan duzenlenmis metin')),
                ('editor_notes', models.TextField(blank=True, default='')),
                ('ai_generated', models.BooleanField(default=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.socialcampaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.socialaccount')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Postu',
                'verbose_name_plural': 'Sosyal Medya Postlari',
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to='social.socialpost')),
            ],
            options={
                'verbose_name': 'Yayinlama Logu',
                'verbose_name_plural': 'Yayinlama Loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['status', 'scheduled_at'], name='social_soci_status_226332_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['platform', 'status'], name='social_soci_platfor_3dc017_idx'),
        ),
    ]
