# Generated by Django 5.1.5 on 2026-02-12 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpilepsyTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_tr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sleep', 'Sleep'), ('stress', 'Stress'), ('substance', 'Substance'), ('sensory', 'Sensory'), ('physical', 'Physical'), ('hormonal', 'Hormonal'), ('other', 'Other')], default='other', max_length=20)),
                ('is_predefined', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_epilepsy_triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='SeizureEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seizure_datetime', models.DateTimeField()),
                ('seizure_type', models.CharField(choices=[('focal_aware', 'Focal Aware'), ('focal_impaired', 'Focal Impaired Awareness'), ('generalized_tonic_clonic', 'Generalized Tonic-Clonic'), ('generalized_absence', 'Absence'), ('generalized_myoclonic', 'Myoclonic'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('intensity', models.PositiveSmallIntegerField(help_text='1-10 scale')),
                ('loss_of_consciousness', models.BooleanField(default=False)),
                ('medication_taken', models.BooleanField(default=True)),
                ('post_ictal_notes', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seizure_events', to=settings.AUTH_USER_MODEL)),
                ('triggers_identified', models.ManyToManyField(blank=True, related_name='seizure_events', to='epilepsy.epilepsytrigger')),
            ],
            options={
                'ordering': ['-seizure_datetime'],
                'indexes': [models.Index(fields=['patient', '-seizure_datetime'], name='epilepsy_se_patient_b275ad_idx')],
            },
        ),
    ]
