# Generated by Django 6.0.1 on 2026-01-27 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_tr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.contentcategory')),
            ],
            options={
                'verbose_name_plural': 'Content categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title_tr', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('body_tr', models.TextField(blank=True, default='')),
                ('body_en', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('infographic', 'Infographic'), ('interactive', 'Interactive')], max_length=20)),
                ('video_url', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='education/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_items', to='content.contentcategory')),
                ('disease_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_items', to='patients.diseasemodule')),
            ],
            options={
                'ordering': ['disease_module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title_tr', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('excerpt_tr', models.TextField(blank=True, default='')),
                ('excerpt_en', models.TextField(blank=True, default='')),
                ('body_tr', models.TextField()),
                ('body_en', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='articles/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title_tr', models.CharField(blank=True, default='', max_length=200)),
                ('seo_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description_tr', models.TextField(blank=True, default='')),
                ('seo_description_en', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.contentcategory')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='content_art_status_9dc828_idx'), models.Index(fields=['slug'], name='content_art_slug_d82f31_idx')],
            },
        ),
        migrations.CreateModel(
            name='EducationProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('education_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content.educationitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'education_item')},
            },
        ),
    ]
