# Generated by Django 5.1.5 on 2026-02-13 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorauthor'),
        ('content', '0001_initial'),
        ('patients', '0001_initial'),
        ('store', '0002_physicalproduct_softwareproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('title_tr', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, default='', max_length=300)),
                ('excerpt_tr', models.TextField(blank=True, default='', max_length=500)),
                ('excerpt_en', models.TextField(blank=True, default='', max_length=500)),
                ('body_tr', models.TextField()),
                ('body_en', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('fda_approval', 'FDA Onayi'), ('ema_approval', 'EMA Onayi'), ('turkey_approval', 'Turkiye Ruhsat'), ('clinical_trial', 'Klinik Calisma Sonucu'), ('new_device', 'Yeni Cihaz / Teknoloji'), ('congress', 'Kongre Haberi'), ('turkey_news', 'Turkiye Guncel'), ('popular_science', 'Populer Bilim'), ('drug_update', 'Ilac Guncellemesi'), ('guideline_update', 'Kilavuz Guncellemesi')], max_length=30)),
                ('priority', models.CharField(choices=[('urgent', 'Acil'), ('high', 'Yuksek'), ('medium', 'Orta'), ('low', 'Dusuk')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('review', 'Incelemede'), ('revision', 'Duzeltme Bekliyor'), ('approved', 'Onaylandi'), ('published', 'Yayinda'), ('archived', 'Arsivlendi')], default='draft', max_length=15)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('original_source', models.CharField(blank=True, default='', max_length=200)),
                ('meta_title', models.CharField(blank=True, default='', max_length=70)),
                ('meta_description', models.CharField(blank=True, default='', max_length=160)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('schema_markup', models.JSONField(blank=True, default=dict)),
                ('featured_image', models.ImageField(blank=True, upload_to='news_images/')),
                ('featured_image_alt', models.CharField(blank=True, default='', max_length=200)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='accounts.doctorauthor')),
                ('related_diseases', models.ManyToManyField(blank=True, related_name='news_articles', to='patients.diseasemodule')),
                ('related_products', models.ManyToManyField(blank=True, related_name='news_articles', to='store.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('agent', 'Ajan Degerlendirmesi'), ('editor', 'Editor Degerlendirmesi'), ('chief_editor', 'Bas Editor Degerlendirmesi')], max_length=15)),
                ('medical_accuracy_score', models.IntegerField(default=0)),
                ('language_quality_score', models.IntegerField(default=0)),
                ('seo_score', models.IntegerField(default=0)),
                ('style_compliance_score', models.IntegerField(default=0)),
                ('ethics_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('decision', models.CharField(choices=[('publish', 'Yayinla'), ('revise', 'Duzeltme Gerekli'), ('reject', 'Reddet')], max_length=10)),
                ('feedback', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('detailed_analysis', models.JSONField(blank=True, default=dict)),
                ('promotion_flags', models.JSONField(blank=True, default=list)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.article')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('news_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.newsarticle')),
            ],
            options={
                'verbose_name': 'Yazi Degerlendirmesi',
                'verbose_name_plural': 'Yazi Degerlendirmeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
