# Generated by Django 5.1.5 on 2026-03-11 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_doctor_author_fk'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title_tr', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('description_tr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('passing_score_percent', models.PositiveSmallIntegerField(default=60)),
                ('points_reward', models.PositiveIntegerField(default=10)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='content.contentcategory')),
                ('disease_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_quizzes', to='patients.diseasemodule')),
                ('education_items', models.ManyToManyField(blank=True, related_name='quizzes', to='content.educationitem')),
            ],
            options={
                'verbose_name': 'Egitim Quiz',
                'verbose_name_plural': 'Egitim Quizler',
                'ordering': ['disease_module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_tr', models.TextField()),
                ('question_en', models.TextField()),
                ('options', models.JSONField(help_text='[{text_tr, text_en, is_correct}] listesi')),
                ('explanation_tr', models.TextField(blank=True, default='')),
                ('explanation_en', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.educationquiz')),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=list, help_text='[{question_id, selected_option_index, is_correct}]')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.educationquiz')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='content_qui_patient_e47636_idx'), models.Index(fields=['quiz', 'patient'], name='content_qui_quiz_id_2cdb14_idx')],
            },
        ),
    ]
