# Generated by Django 5.1.5 on 2026-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_educationquiz_quizquestion_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_url',
            field=models.URLField(blank=True, default='', help_text='Harici gorsel URL (Unsplash/Pexels)', max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='featured_image_url',
            field=models.URLField(blank=True, default='', help_text='Harici gorsel URL (Unsplash/Pexels)', max_length=500),
        ),
    ]
