from django.core.management.base import BaseCommand
from apps.gamification.models import Badge, Achievement


class Command(BaseCommand):
    help = 'Seed gamification data (badges and achievements)'

    def handle(self, *args, **options):
        self.seed_badges()
        self.seed_achievements()
        self.stdout.write(self.style.SUCCESS('Gamification data seeded successfully!'))

    def seed_badges(self):
        badges = [
            # Tracking badges
            {
                'name_tr': 'İlk Adım',
                'name_en': 'First Step',
                'description_tr': 'İlk migren atağını kaydettin!',
                'description_en': 'You logged your first migraine attack!',
                'icon': 'footprints',
                'color': 'green',
                'category': 'tracking',
                'rarity': 'common',
                'points_reward': 10,
                'requirement_type': 'total_attacks_logged',
                'requirement_value': 1,
            },
            {
                'name_tr': 'Düzenli Takipçi',
                'name_en': 'Regular Tracker',
                'description_tr': '10 migren atağı kaydettin.',
                'description_en': 'You logged 10 migraine attacks.',
                'icon': 'clipboard-list',
                'color': 'blue',
                'category': 'tracking',
                'rarity': 'uncommon',
                'points_reward': 25,
                'requirement_type': 'total_attacks_logged',
                'requirement_value': 10,
            },
            {
                'name_tr': 'Veri Ustası',
                'name_en': 'Data Master',
                'description_tr': '50 migren atağı kaydettin.',
                'description_en': 'You logged 50 migraine attacks.',
                'icon': 'database',
                'color': 'purple',
                'category': 'tracking',
                'rarity': 'rare',
                'points_reward': 50,
                'requirement_type': 'total_attacks_logged',
                'requirement_value': 50,
            },
            # Streak badges
            {
                'name_tr': 'Bir Hafta Serisi',
                'name_en': 'Week Streak',
                'description_tr': '7 gün üst üste kayıt yaptın!',
                'description_en': 'You logged for 7 consecutive days!',
                'icon': 'flame',
                'color': 'orange',
                'category': 'streak',
                'rarity': 'common',
                'points_reward': 20,
                'requirement_type': 'streak_days',
                'requirement_value': 7,
            },
            {
                'name_tr': 'Bir Ay Serisi',
                'name_en': 'Month Streak',
                'description_tr': '30 gün üst üste kayıt yaptın!',
                'description_en': 'You logged for 30 consecutive days!',
                'icon': 'fire',
                'color': 'red',
                'category': 'streak',
                'rarity': 'rare',
                'points_reward': 100,
                'requirement_type': 'streak_days',
                'requirement_value': 30,
            },
            {
                'name_tr': 'Efsane Seri',
                'name_en': 'Legendary Streak',
                'description_tr': '100 gün üst üste kayıt yaptın!',
                'description_en': 'You logged for 100 consecutive days!',
                'icon': 'crown',
                'color': 'gold',
                'category': 'streak',
                'rarity': 'legendary',
                'points_reward': 500,
                'requirement_type': 'streak_days',
                'requirement_value': 100,
            },
            # Wellness badges
            {
                'name_tr': 'Nefes Ustası',
                'name_en': 'Breathing Master',
                'description_tr': '10 nefes egzersizi tamamladın.',
                'description_en': 'You completed 10 breathing exercises.',
                'icon': 'wind',
                'color': 'cyan',
                'category': 'wellness',
                'rarity': 'uncommon',
                'points_reward': 30,
                'requirement_type': 'breathing_sessions',
                'requirement_value': 10,
            },
            {
                'name_tr': 'Zen Ustası',
                'name_en': 'Zen Master',
                'description_tr': '20 gevşeme egzersizi tamamladın.',
                'description_en': 'You completed 20 relaxation exercises.',
                'icon': 'spa',
                'color': 'purple',
                'category': 'wellness',
                'rarity': 'rare',
                'points_reward': 50,
                'requirement_type': 'relaxation_sessions',
                'requirement_value': 20,
            },
            {
                'name_tr': 'Su İçici',
                'name_en': 'Water Drinker',
                'description_tr': '7 gün üst üste su hedefini tamamladın.',
                'description_en': 'You met your water goal for 7 consecutive days.',
                'icon': 'droplet',
                'color': 'blue',
                'category': 'wellness',
                'rarity': 'uncommon',
                'points_reward': 25,
                'requirement_type': 'water_goal_streak',
                'requirement_value': 7,
            },
            {
                'name_tr': 'Uyku Düzencisi',
                'name_en': 'Sleep Scheduler',
                'description_tr': '14 gün uyku kaydı tuttun.',
                'description_en': 'You kept sleep records for 14 days.',
                'icon': 'moon',
                'color': 'indigo',
                'category': 'wellness',
                'rarity': 'uncommon',
                'points_reward': 30,
                'requirement_type': 'sleep_logs',
                'requirement_value': 14,
            },
            # Milestone badges
            {
                'name_tr': 'Tetikleyici Dedektifi',
                'name_en': 'Trigger Detective',
                'description_tr': 'En az 5 farklı tetikleyici belirledin.',
                'description_en': 'You identified at least 5 different triggers.',
                'icon': 'search',
                'color': 'yellow',
                'category': 'milestone',
                'rarity': 'uncommon',
                'points_reward': 35,
                'requirement_type': 'unique_triggers',
                'requirement_value': 5,
            },
            {
                'name_tr': 'Seviye 5',
                'name_en': 'Level 5',
                'description_tr': 'Seviye 5e ulaştın!',
                'description_en': 'You reached Level 5!',
                'icon': 'star',
                'color': 'yellow',
                'category': 'milestone',
                'rarity': 'uncommon',
                'points_reward': 50,
                'requirement_type': 'level',
                'requirement_value': 5,
            },
            {
                'name_tr': 'Seviye 10',
                'name_en': 'Level 10',
                'description_tr': 'Seviye 10a ulaştın!',
                'description_en': 'You reached Level 10!',
                'icon': 'trophy',
                'color': 'gold',
                'category': 'milestone',
                'rarity': 'epic',
                'points_reward': 100,
                'requirement_type': 'level',
                'requirement_value': 10,
            },
        ]

        for badge_data in badges:
            Badge.objects.update_or_create(
                name_tr=badge_data['name_tr'],
                defaults=badge_data
            )
        self.stdout.write(f'  Created {len(badges)} badges')

    def seed_achievements(self):
        achievements = [
            # Daily achievements
            {
                'name_tr': 'Günlük Kayıt',
                'name_en': 'Daily Log',
                'description_tr': 'Bugün en az bir sağlık kaydı yap.',
                'description_en': 'Make at least one health log today.',
                'icon': 'calendar-check',
                'color': 'green',
                'period': 'daily',
                'target_type': 'any_log',
                'target_value': 1,
                'points_reward': 5,
            },
            {
                'name_tr': 'Su Hedefi',
                'name_en': 'Water Goal',
                'description_tr': 'Günlük su hedefini tamamla (8 bardak).',
                'description_en': 'Complete daily water goal (8 glasses).',
                'icon': 'droplet',
                'color': 'blue',
                'period': 'daily',
                'target_type': 'water_glasses',
                'target_value': 8,
                'points_reward': 5,
            },
            {
                'name_tr': 'Nefes Molası',
                'name_en': 'Breathing Break',
                'description_tr': 'Bir nefes egzersizi tamamla.',
                'description_en': 'Complete one breathing exercise.',
                'icon': 'wind',
                'color': 'cyan',
                'period': 'daily',
                'target_type': 'breathing_exercise',
                'target_value': 1,
                'points_reward': 5,
            },
            # Weekly achievements
            {
                'name_tr': 'Haftalık Takipçi',
                'name_en': 'Weekly Tracker',
                'description_tr': 'Bu hafta 5 gün kayıt yap.',
                'description_en': 'Log for 5 days this week.',
                'icon': 'calendar',
                'color': 'purple',
                'period': 'weekly',
                'target_type': 'daily_logs',
                'target_value': 5,
                'points_reward': 20,
            },
            {
                'name_tr': 'Wellness Haftası',
                'name_en': 'Wellness Week',
                'description_tr': 'Bu hafta 3 gevşeme egzersizi tamamla.',
                'description_en': 'Complete 3 relaxation exercises this week.',
                'icon': 'spa',
                'color': 'pink',
                'period': 'weekly',
                'target_type': 'relaxation_sessions',
                'target_value': 3,
                'points_reward': 15,
            },
            {
                'name_tr': 'Uyku Düzeni',
                'name_en': 'Sleep Schedule',
                'description_tr': 'Bu hafta her gün uyku kaydı yap.',
                'description_en': 'Log sleep every day this week.',
                'icon': 'moon',
                'color': 'indigo',
                'period': 'weekly',
                'target_type': 'sleep_logs',
                'target_value': 7,
                'points_reward': 25,
            },
            # Monthly achievements
            {
                'name_tr': 'Ay Yıldızı',
                'name_en': 'Monthly Star',
                'description_tr': 'Bu ay 20 gün kayıt yap.',
                'description_en': 'Log for 20 days this month.',
                'icon': 'star',
                'color': 'yellow',
                'period': 'monthly',
                'target_type': 'daily_logs',
                'target_value': 20,
                'points_reward': 50,
            },
            {
                'name_tr': 'Wellness Şampiyonu',
                'name_en': 'Wellness Champion',
                'description_tr': 'Bu ay 15 egzersiz seansı tamamla.',
                'description_en': 'Complete 15 exercise sessions this month.',
                'icon': 'trophy',
                'color': 'gold',
                'period': 'monthly',
                'target_type': 'total_exercise_sessions',
                'target_value': 15,
                'points_reward': 75,
            },
            # One-time achievements
            {
                'name_tr': 'Profil Tamamlayıcı',
                'name_en': 'Profile Completer',
                'description_tr': 'Profilini tamamen doldur.',
                'description_en': 'Complete your profile fully.',
                'icon': 'user-check',
                'color': 'green',
                'period': 'one_time',
                'target_type': 'profile_complete',
                'target_value': 1,
                'points_reward': 25,
            },
            {
                'name_tr': 'İlk Rapor',
                'name_en': 'First Report',
                'description_tr': 'İlk PDF raporunu oluştur.',
                'description_en': 'Generate your first PDF report.',
                'icon': 'file-text',
                'color': 'red',
                'period': 'one_time',
                'target_type': 'pdf_report',
                'target_value': 1,
                'points_reward': 15,
            },
        ]

        for ach_data in achievements:
            Achievement.objects.update_or_create(
                name_tr=ach_data['name_tr'],
                defaults=ach_data
            )
        self.stdout.write(f'  Created {len(achievements)} achievements')
