# Generated by Django 6.0.1 on 2026-01-29 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('inhale_seconds', models.PositiveIntegerField(default=4)),
                ('hold_seconds', models.PositiveIntegerField(default=4)),
                ('exhale_seconds', models.PositiveIntegerField(default=4)),
                ('hold_after_exhale_seconds', models.PositiveIntegerField(default=0)),
                ('cycles', models.PositiveIntegerField(default=5)),
                ('difficulty', models.CharField(choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri')], default='beginner', max_length=20)),
                ('benefits_tr', models.TextField(blank=True)),
                ('benefits_en', models.TextField(blank=True)),
                ('icon', models.CharField(default='lungs', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name_tr'],
            },
        ),
        migrations.CreateModel(
            name='RelaxationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('exercise_type', models.CharField(choices=[('pmr', 'Progresif Kas Gevşetme'), ('body_scan', 'Vücut Tarama'), ('visualization', 'Görselleştirme'), ('grounding', 'Topraklama'), ('mindfulness', 'Farkındalık')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('steps_tr', models.JSONField(default=list)),
                ('steps_en', models.JSONField(default=list)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('benefits_tr', models.TextField(blank=True)),
                ('benefits_en', models.TextField(blank=True)),
                ('icon', models.CharField(default='spa', max_length=50)),
                ('color', models.CharField(default='purple', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name_tr'],
            },
        ),
        migrations.CreateModel(
            name='UserWeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Istanbul', max_length=100)),
                ('country_code', models.CharField(default='TR', max_length=5)),
                ('alert_on_pressure_drop', models.BooleanField(default=True)),
                ('pressure_threshold', models.FloatField(default=5.0)),
                ('alert_on_humidity_high', models.BooleanField(default=True)),
                ('humidity_threshold', models.PositiveIntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='TR', max_length=5)),
                ('temperature', models.FloatField()),
                ('humidity', models.PositiveIntegerField()),
                ('pressure', models.FloatField()),
                ('weather_condition', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['city', '-recorded_at'], name='wellness_we_city_e83033_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenstrualLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_period_day', models.BooleanField(default=True)),
                ('flow_intensity', models.CharField(blank=True, choices=[('spotting', 'Lekelenme'), ('light', 'Hafif'), ('medium', 'Orta'), ('heavy', 'Yoğun')], max_length=20)),
                ('has_cramps', models.BooleanField(default=False)),
                ('cramp_intensity', models.PositiveIntegerField(blank=True, null=True)),
                ('has_headache', models.BooleanField(default=False)),
                ('has_mood_changes', models.BooleanField(default=False)),
                ('has_bloating', models.BooleanField(default=False)),
                ('has_fatigue', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='wellness_me_user_id_9bb9ef_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('stress_before', models.PositiveIntegerField(blank=True, null=True)),
                ('stress_after', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('breathing_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wellness.breathingexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relaxation_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wellness.relaxationexercise')),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='wellness_ex_user_id_826a86_idx')],
            },
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bedtime', models.TimeField()),
                ('wake_time', models.TimeField()),
                ('sleep_duration_minutes', models.PositiveIntegerField()),
                ('sleep_quality', models.PositiveIntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')])),
                ('had_nightmare', models.BooleanField(default=False)),
                ('woke_up_during_night', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='wellness_sl_user_id_b014b3_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WaterIntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('glasses', models.PositiveIntegerField(default=0)),
                ('target_glasses', models.PositiveIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-date'], name='wellness_wa_user_id_3356e8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
