# Generated by Django 5.1.5 on 2026-02-13 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_grams', models.PositiveIntegerField(default=0)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('technical_specs', models.JSONField(blank=True, default=dict)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('shipping_info', models.JSONField(blank=True, default=dict)),
                ('ships_internationally', models.BooleanField(default=True)),
                ('manufacturer', models.CharField(default='UlgarTech', max_length=200)),
                ('manufacturing_country', models.CharField(default='Turkiye', max_length=50)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_details', to='store.product')),
            ],
            options={
                'verbose_name': 'Fiziksel Urun',
                'verbose_name_plural': 'Fiziksel Urunler',
            },
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.CharField(default='1.0.0', max_length=20)),
                ('changelog', models.JSONField(blank=True, default=list)),
                ('supported_platforms', models.JSONField(blank=True, default=list)),
                ('system_requirements_json', models.JSONField(blank=True, default=dict)),
                ('demo_url', models.URLField(blank=True, default='')),
                ('demo_video_url', models.URLField(blank=True, default='')),
                ('documentation_url', models.URLField(blank=True, default='')),
                ('pricing_plans', models.JSONField(blank=True, default=list)),
                ('apple_store_url', models.URLField(blank=True, default='')),
                ('apple_store_id', models.CharField(blank=True, default='', max_length=50)),
                ('academic_references', models.JSONField(blank=True, default=list)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software_details', to='store.product')),
            ],
            options={
                'verbose_name': 'Yazilim Urunu',
                'verbose_name_plural': 'Yazilim Urunleri',
            },
        ),
    ]
