# Generated by Django 6.0.1 on 2026-01-27 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('disease_type', models.CharField(choices=[('migraine', 'Migraine'), ('epilepsy', 'Epilepsy'), ('parkinson', 'Parkinson'), ('dementia', 'Dementia')], max_length=20, unique=True)),
                ('name_tr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description_tr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_tr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('diary_entry', 'Diary Entry'), ('checklist', 'Checklist'), ('education', 'Education'), ('exercise', 'Exercise'), ('medication', 'Medication'), ('survey', 'Survey')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('on_event', 'On Event'), ('one_time', 'One Time')], max_length=20)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('disease_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='patients.diseasemodule')),
            ],
            options={
                'ordering': ['disease_module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PatientModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disease_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_patients', to='patients.diseasemodule')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'disease_module')},
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateField()),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='patients.tasktemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', '-completed_date'], name='patients_ta_patient_4898e8_idx'), models.Index(fields=['task_template', 'patient'], name='patients_ta_task_te_d3b293_idx')],
            },
        ),
    ]
