# Generated by Django 5.1.5 on 2026-02-13 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_specialty', models.CharField(choices=[('neurology', 'Noroloji'), ('ftr', 'Fiziksel Tip ve Rehabilitasyon'), ('neurosurgery', 'Beyin ve Sinir Cerrahisi'), ('physiology', 'Fizyoloji'), ('geriatrics', 'Geriatri'), ('psychiatry', 'Psikiyatri'), ('sleep_medicine', 'Uyku Bozukluklari'), ('clinical_psychology', 'Klinik Psikoloji'), ('social_work', 'Sosyal Hizmet')], max_length=30)),
                ('secondary_specialties', models.JSONField(blank=True, default=list)),
                ('sub_specialties', models.JSONField(blank=True, default=list)),
                ('bio_tr', models.TextField(blank=True, default='')),
                ('bio_en', models.TextField(blank=True, default='')),
                ('headline_tr', models.CharField(blank=True, default='', max_length=200)),
                ('headline_en', models.CharField(blank=True, default='', max_length=200)),
                ('education', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('memberships', models.JSONField(blank=True, default=list)),
                ('orcid_id', models.CharField(blank=True, default='', max_length=50)),
                ('google_scholar_url', models.URLField(blank=True, default='')),
                ('pubmed_author_id', models.CharField(blank=True, default='', max_length=50)),
                ('institution', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('author_level', models.IntegerField(choices=[(0, 'Yeni Yazar'), (1, 'Onayli Yazar'), (2, 'Aktif Yazar'), (3, 'Kidemli Yazar'), (4, 'Editor')], default=0)),
                ('total_articles', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_document', models.FileField(blank=True, upload_to='doctor_verification/')),
                ('profile_photo', models.ImageField(blank=True, upload_to='doctor_photos/')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to='accounts.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doktor Yazar',
                'verbose_name_plural': 'Doktor Yazarlar',
                'ordering': ['-author_level', '-total_articles'],
            },
        ),
    ]
