# Generated by Django 5.1.5 on 2026-03-08 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('caregiver', 'Caregiver')], default='patient', max_length=10),
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('sibling', 'Sibling'), ('professional', 'Professional Caregiver'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('patients', models.ManyToManyField(blank=True, limit_choices_to={'role': 'patient'}, related_name='caregivers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caregiver Profile',
                'verbose_name_plural': 'Caregiver Profiles',
            },
        ),
    ]
