# Generated by Django 5.1.5 on 2026-03-12 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_caregiver_role_and_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('caregiver', 'Caregiver'), ('relative', 'Relative')], default='patient', max_length=12),
        ),
        migrations.CreateModel(
            name='RelativeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('grandchild', 'Grandchild'), ('other', 'Other')], default='other', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_relatives', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relative_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relative Profile',
                'verbose_name_plural': 'Relative Profiles',
                'unique_together': {('user', 'patient')},
            },
        ),
    ]
