# Generated by Django 5.1.5 on 2026-03-12 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_relative_role_and_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativeInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('invited_name', models.CharField(blank=True, default='', max_length=150)),
                ('relationship_type', models.CharField(choices=[('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('grandchild', 'Grandchild'), ('other', 'Other')], default='other', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_relative_invitations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='relative_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relative Invitation',
                'verbose_name_plural': 'Relative Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
