# Generated by Django 5.1.5 on 2026-03-14 14:49

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_doctors(apps, schema_editor):
    """Mark all existing doctor profiles as approved so they are not locked out."""
    DoctorProfile = apps.get_model('accounts', 'DoctorProfile')
    DoctorProfile.objects.all().update(approval_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_relative_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandi'), ('rejected', 'Reddedildi')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        # Mark all existing doctors as approved
        migrations.RunPython(approve_existing_doctors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='doctorauthor',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='doctor_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.common.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='doctorauthor',
            name='verification_document',
            field=models.FileField(blank=True, upload_to='doctor_verification/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), apps.common.validators.validate_document_file_size]),
        ),
    ]
