# Generated by Django 5.1.5 on 2026-01-30 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_tr', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description_tr', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('instructions_tr', models.TextField(blank=True, default='')),
                ('instructions_en', models.TextField(blank=True, default='')),
                ('exercise_type', models.CharField(choices=[('memory', 'Memory Game'), ('attention', 'Attention Test'), ('language', 'Language Exercise'), ('problem_solving', 'Problem Solving'), ('orientation', 'Orientation'), ('calculation', 'Calculation')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=5)),
                ('icon', models.CharField(default='brain', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('observation', 'Observation'), ('concern', 'Concern'), ('improvement', 'Improvement'), ('incident', 'Incident'), ('medication', 'Medication Related'), ('behavior', 'Behavior Change'), ('other', 'Other')], default='observation', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='1=Low, 2=Medium, 3=High')),
                ('is_flagged_for_doctor', models.BooleanField(default=False)),
                ('doctor_reviewed', models.BooleanField(default=False)),
                ('doctor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='dementia_ca_patient_1efed6_idx'), models.Index(fields=['is_flagged_for_doctor', 'doctor_reviewed'], name='dementia_ca_is_flag_584ca6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CognitiveScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_date', models.DateField()),
                ('memory_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attention_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('language_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('problem_solving_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('orientation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exercises_completed', models.PositiveIntegerField(default=0)),
                ('total_exercise_minutes', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score_date'],
                'unique_together': {('patient', 'score_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateField()),
                ('mood_score', models.PositiveSmallIntegerField(blank=True, help_text='1=Very poor, 5=Excellent', null=True)),
                ('confusion_level', models.PositiveSmallIntegerField(blank=True, help_text='1=None, 5=Severe', null=True)),
                ('agitation_level', models.PositiveSmallIntegerField(blank=True, help_text='1=None, 5=Severe', null=True)),
                ('anxiety_level', models.PositiveSmallIntegerField(blank=True, help_text='1=None, 5=Severe', null=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, help_text='1=Very poor, 5=Excellent', null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('night_wandering', models.BooleanField(blank=True, null=True)),
                ('eating_independence', models.PositiveSmallIntegerField(blank=True, help_text='1=Full assistance, 5=Independent', null=True)),
                ('dressing_independence', models.PositiveSmallIntegerField(blank=True, help_text='1=Full assistance, 5=Independent', null=True)),
                ('hygiene_independence', models.PositiveSmallIntegerField(blank=True, help_text='1=Full assistance, 5=Independent', null=True)),
                ('mobility_independence', models.PositiveSmallIntegerField(blank=True, help_text='1=Full assistance, 5=Independent', null=True)),
                ('verbal_communication', models.PositiveSmallIntegerField(blank=True, help_text='1=None, 5=Normal', null=True)),
                ('recognition_family', models.BooleanField(blank=True, help_text='Recognizes family members', null=True)),
                ('fall_occurred', models.BooleanField(default=False)),
                ('wandering_occurred', models.BooleanField(default=False)),
                ('medication_missed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('concerns', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assessments', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date'],
                'indexes': [models.Index(fields=['patient', '-assessment_date'], name='dementia_da_patient_84ca22_idx')],
                'unique_together': {('patient', 'assessment_date')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_possible_score', models.PositiveIntegerField(default=100)),
                ('accuracy_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, help_text='Patient rating: 1=too easy, 2=good, 3=too hard', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dementia.cognitiveexercise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['patient', '-started_at'], name='dementia_ex_patient_2a7014_idx'), models.Index(fields=['exercise', 'patient'], name='dementia_ex_exercis_0bb82f_idx')],
            },
        ),
    ]
