# Generated by Django 5.1.5 on 2026-02-15 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateField()),
                ('orientation_score', models.DecimalField(blank=True, decimal_places=2, help_text='Time and place awareness', max_digits=5, null=True)),
                ('memory_score', models.DecimalField(blank=True, decimal_places=2, help_text='Short-term and recall memory', max_digits=5, null=True)),
                ('attention_score', models.DecimalField(blank=True, decimal_places=2, help_text='Focus and concentration', max_digits=5, null=True)),
                ('language_score', models.DecimalField(blank=True, decimal_places=2, help_text='Naming and comprehension', max_digits=5, null=True)),
                ('executive_score', models.DecimalField(blank=True, decimal_places=2, help_text='Planning and problem solving', max_digits=5, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_screenings', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_screenings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date'],
                'indexes': [models.Index(fields=['patient', '-assessment_date'], name='dementia_co_patient_ca2904_idx')],
            },
        ),
    ]
