# Generated by Django 5.1.5 on 2026-03-08 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia', '0002_cognitivescreening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('sibling', 'Sibling'), ('parent', 'Parent'), ('doctor', 'Doctor'), ('other', 'Other')], default='other', max_length=20)),
                ('notify_via', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('both', 'Both')], default='email', max_length=10)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('consent_given_at', models.DateTimeField(blank=True, help_text='KVKK explicit consent timestamp', null=True)),
                ('consent_text', models.TextField(blank=True, default='', help_text='Consent text shown to user at the time of approval')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportShareRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('share_type', models.CharField(max_length=10)),
                ('report_period_start', models.DateField()),
                ('report_period_end', models.DateField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_version', models.CharField(default='1.0', max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_shares', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_records', to='dementia.reportrecipient')),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportrecipient',
            index=models.Index(fields=['patient', 'is_active'], name='dementia_re_patient_d32596_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsharerecord',
            index=models.Index(fields=['patient', '-shared_at'], name='dementia_re_patient_065893_idx'),
        ),
    ]
