# Generated by Django 5.1.5 on 2026-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('tracking', 'Takip'), ('streak', 'Seri'), ('milestone', 'Kilometre Taşı'), ('wellness', 'Sağlık'), ('social', 'Sosyal'), ('education', 'Eğitim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='streak_type',
            field=models.CharField(choices=[('daily_log', 'Günlük Kayıt'), ('migraine_diary', 'Migren Günlüğü'), ('water_intake', 'Su Tüketimi'), ('sleep_log', 'Uyku Kaydı'), ('exercise', 'Egzersiz'), ('education', 'Eğitim')], max_length=30),
        ),
    ]
